INSERT INTO performers(name) VALUES('Linkin Park');
INSERT INTO performers(name) VALUES('The Cranberries');
INSERT INTO performers(name) VALUES('Within Temptation');
INSERT INTO performers(name) VALUES('Adele');
INSERT INTO performers(name) VALUES('The Pretty Reckless');
INSERT INTO performers(name) VALUES('Sia');
INSERT INTO performers(name) VALUES('AC/DC');
INSERT INTO performers(name) VALUES('Ray Charles');
INSERT INTO performers(name) VALUES('Whitney Houston');

INSERT INTO jenre(name, description) VALUES('Хард-Рок', 'Жанр рок-музыки, характеризующийся выделенной ролью ритм-секции, главным образом бас-гитары и ударных инструментов. Композиции этого жанра часто построены на риффах в фигурах с размером 4/4');
INSERT INTO jenre(name, description) VALUES('Альтернативный рок', 'Жанр рок-музыки, сформировавшийся из музыкального андеграунда 1980-х и ставший популярным в 1990-е и 2000-е годы.');
INSERT INTO jenre(name, description) VALUES('Симфонический рок', 'Разновидность прогрессивного рока. Термин был предложен для обозначения прогрессивных групп, более всего сориентированных на академический подход к музыке');
INSERT INTO jenre(name, description) VALUES('Поп', 'Это жанр популярной музыки, который возник в его современном виде в западных странах в качестве более мягкой альтернативы рок-н-роллу.');
INSERT INTO jenre(name, description) VALUES('Соул', 'Жанр популярной музыки афро-американского происхождения, возникший в южных штатах США в 1950-е годы на основе ритм-энд-блюза');
INSERT INTO jenre(name, description) VALUES('Джаз', 'Род музыкального искусства, сложившийся под влиянием африканских ритмов, европейской гармонии, с привлечением элементов афроамериканского фольклора');
INSERT INTO jenre(name, description) VALUES('R&B', 'Стиль популярной музыки афроамериканцев, включающий элементы блюза. Изначально, обобщённое название массовой музыки, основанной на блюзовых и джазовых направлениях 1930—1940-х годов');

INSERT INTO albums(title, year_of_release) VALUES('Meteora', 2003); 
INSERT INTO albums(title, year_of_release) VALUES('Hybrid Theory', 2000); 
INSERT INTO albums(title, year_of_release) VALUES('20th Century Masters', 2009); 
INSERT INTO albums(title, year_of_release) VALUES('19', 2008);
INSERT INTO albums(title, year_of_release) VALUES('25', 2015);
INSERT INTO albums(title, year_of_release) VALUES('Going to Hell', 2014);
INSERT INTO albums(title, year_of_release) VALUES('This Is Acting', 2016);
INSERT INTO albums(title, year_of_release) VALUES('Back In Black', 1980);
INSERT INTO albums(title, year_of_release) VALUES('Legend', 2018);
INSERT INTO albums(title, year_of_release) VALUES('I Look To You', 2009);
INSERT INTO albums(title, year_of_release) VALUES('Resist', 2019);
INSERT INTO albums(title, year_of_release) VALUES('The Unforgiving', 2011);
INSERT INTO albums(title, year_of_release) VALUES('Shed My Skin', 2020);

INSERT INTO tracks(title, duration, single, album_id) VALUES('Faint', 164, false, 1);
INSERT INTO tracks(title, duration, single, album_id) VALUES('In the End', 216, false, 2);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Animal Instinct', 211, false, 3);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Zombie', 307, false, 3);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Endless War', 249, false, 11);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Supernova', 336, false, 11);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Shot in the Dark', 302, false, 12);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Faster', 263, false, 12);
INSERT INTO tracks(title, duration, single, album_id) VALUES('My Same', 195, false, 4);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Hello', 295, false, 5);
INSERT INTO tracks(title, duration, single, album_id) VALUES('House on a Hill', 285, false, 6);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Absolution', 274, false, 6);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Bird Set Free', 252, false, 7);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Unstoppable', 217, false, 7);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Hells Bells', 312, false, 8);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Back in Black', 255, false, 8);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Hit the Road Jack', 118, false, 9);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Unchain My Heart', 173, false, 9);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Call You Tonight', 248, false, 10);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Million Dollar Bill', 204, false, 10);
INSERT INTO tracks(title, duration, single, album_id) VALUES('The Purge', 256, false, 13);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Entertain You', 211, false, 13);
INSERT INTO tracks(title, duration, single, album_id) VALUES('Salvation', 118, false, 3);

INSERT INTO collections(title, year_of_release) VALUES('From the Heart', 2021); 
INSERT INTO collections(title, year_of_release) VALUES('The Good Comrade', 2021); 
INSERT INTO collections(title, year_of_release) VALUES('Golden Years', 2019); 
INSERT INTO collections(title, year_of_release) VALUES('Summer Music Fest', 2018); 
INSERT INTO collections(title, year_of_release) VALUES('Wonderful', 2016);
INSERT INTO collections(title, year_of_release) VALUES('Beloved', 2013);
INSERT INTO collections(title, year_of_release) VALUES('Songs for All Ages', 2020);
INSERT INTO collections(title, year_of_release) VALUES('The Coolest Rhythm', 2015);

INSERT INTO collectionstracks(collection_id, track_id) VALUES(1, 1);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(1, 9);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(2, 2);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(2, 10);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(2, 17);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(3, 3);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(3, 11);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(4, 4);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(4, 12);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(4, 18);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(5, 5);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(5, 13);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(6, 6);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(6, 14);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(6, 19);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(7, 7);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(7, 15);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(8, 8);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(8, 16);
INSERT INTO collectionstracks(collection_id, track_id) VALUES(8, 20);

INSERT INTO performersalbums(performer_id, album_id) VALUES(1, 1);
INSERT INTO performersalbums(performer_id, album_id) VALUES(1, 2);
INSERT INTO performersalbums(performer_id, album_id) VALUES(2, 3);
INSERT INTO performersalbums(performer_id, album_id) VALUES(3, 11);
INSERT INTO performersalbums(performer_id, album_id) VALUES(3, 12);
INSERT INTO performersalbums(performer_id, album_id) VALUES(4, 4);
INSERT INTO performersalbums(performer_id, album_id) VALUES(4, 5);
INSERT INTO performersalbums(performer_id, album_id) VALUES(5, 6);
INSERT INTO performersalbums(performer_id, album_id) VALUES(6, 7);
INSERT INTO performersalbums(performer_id, album_id) VALUES(7, 8);
INSERT INTO performersalbums(performer_id, album_id) VALUES(8, 9);
INSERT INTO performersalbums(performer_id, album_id) VALUES(9, 10);
INSERT INTO performersalbums(performer_id, album_id) VALUES(3, 13);

INSERT INTO performersjenre(performer_id, jenre_id) VALUES(1, 2);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(2, 2);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(3, 3);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(4, 4);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(4, 5);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(5, 2);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(6, 4);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(7, 1);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(8, 6);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(9, 4);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(9, 5);
INSERT INTO performersjenre(performer_id, jenre_id) VALUES(9, 7);